snyk/nodejs-runtime-agent

- lib/transmitter.js
- test/e2e.test.js
renaming `vulnerableFunctions` to `filters` to conform with java agent
> fix: renaming `vulnerableFunctions` to `filters`

- lib/ast.js
Moves `var` to `const` or `let`, as IntelliJ decided. Fix a spello.
> chore: remove all remaining 'var'

- lib/ast.js
- lib/snapshot/index.js
- test/debugger.test.js
- test/method_detection.test.js
Switch to a recursive parser, and recurse into object literals. Primarily, we are trying to catch this syntax:
```
module.exports = {
foo() {
// stuff
}
}
```
The first `feat` commit is similar-ish to the previous algorithm, but with some extra blocks stuck on the end. The diff isn't great to read, though.
> Recurse down through JS code

- lib/ast.js
- test/method_detection.test.js
Support member functions declared in classes. This is used in `mime`.
```js
class Moog {
constructor() {}
sampleRate(freq) {}
static lfo() { return 5; }
}
module.exports = Moog;
```
... generates `Moog.prototype.constructor`, `Moog.prototype.sampleRate` and `Moog.prototype.lfo`.
Again, I am not convinced these intermediate names we're using are correct, but they are useful.
Please read only the second commit; the first was done by IntelliJ. It's kinda readable with whitespace disabled: https://github.com/snyk/nodejs-runtime-agent/commit/103270ec5a48a309721f38a13b8f9a907a90a1cb?w=1
A ClassDeclaration contains a ClassBody, which (inside) has a body, which is a list of declarations inside the class. A MethodDefinition is a .. field assignment of a FunctionExpression, which we already …
> Parse class members

- lib/ast.js
- test/method_detection.test.js
Support finding functions in lodash's "function armour":
```js
;(function() {
var runInContext = (function yellow(context) {
function baseMerge() {}
});
var _ = runInContext();
})();
```
In this, we detect `yellow.baseMerge`. This is, again, perhaps not what a node developer would call this method. What should we be generating?
```js
function foo() {
function bar() {}
}
function pink() {
function bar() {}
}
```
These are distinct functions, so it feels like they should have distinct names.
The "extract method" commit sets the stage: An `ExpressionStatement` doesn't really do anything, as far as I can see (this is a pretty typical grammar hack). The old code for reading an `ExpressionStatement` was really reading its embedded `AssignmentStatement`. We already had code to read an …
> Recurse into lodash-style declarations

- lib/ast.js
- lib/debugger-wrapper.js
- package.json
- test/dump.js
- test/method_detection.test.js
Extend the `ast` parser to pick up `MemberExpression` `object`s.
This matters for code like this, which we see in `lodash`:
```js
(function() { function bar() {} }).call(this);
```
The `(function() { function bar() {} })` is the `object` in this case, which they're invoking `call` on.
> Parse MemberExpression objects

- lib/ast.js
- lib/debugger-wrapper.js
- package.json
- test/dump.js
- test/method_detection.test.js
* Track the full location of where a method is declared.
We can use the `start.column` information when setting the breakpoint. Other consumers can use the `end` information. 
* Add a script that allows inspecting the output manually, using the new information.
> Track full location of matches

- lib/ast.js
- test/method-detection.test.js
Detect arrow functions as functions:
```
const parse = (value) => {
console.log("hi!");
};
```
We saw this in `c:ws#v:3.3.0#p:lib/Extensions.js`
Create a file named `foo.js`, containing an arrow function (like the above snippet).
```bash
node test/dump.js foo.js
```
See that it prints nothing before the PR, and that it finds the `parse` function after the PR.
> feat: detect ws-style arrow functions

- lib/ast.js
- test/method-detection.test.js
Previously, we would skip functions declared like:
```js
+function() {
function foo() {}
}(foo);
```
Yes, there is a plus in front of that function. No, it doesn't seem to do anything reasonable.
```js
> +undefined
NaN
> +function(){}
NaN
> +function(){}()
NaN
```
We now process functions declared inside unary operators.
> feat: detect bootstrap's unary plus wrapper

- lib/ast.js
- test/method-detection.test.js
Make the `ast` recurse into raw/top-level function declarations.
We will now see:
```
function foo() {
function bar() {
function baz() {}
}
}
```
As `foo`, `foo.bar`, `foo.bar.baz`.
Unfortunately, this means we will now evaluate a whole lot more code than we did before.
Do we like those names?
> Recurse into all function types

- lib/ast.js
- test/debugger.test.js
- test/method-detection.test.js
Recognise `hooks` inside:
```
;(function () {
}(this, (function () {
function hooks() {}
})));
```
Yes, `moment` really does that.
Please read the two commits independently, and ignore the cleanup commit. I thought `debugger.test.js` was broken, but it's not!
> Support moment-style wrappers

- lib/ast.js
- test/method-detection.test.js
Disable strict parsing, so we can read modules containing e.g. octal numbers.
Those arguments really are the other way around, between `parse()` and `Parser()`.
I have written this exact commit before. If you know where it went, please do let me know. No, really. I'm worried I'm losing it.
> feat: parse in non-strict for e.g. octal

- README.md
Add a `demo` section to the README, below the developer setup documentation.
I'm expecting most people to consume this readme via. https://www.npmjs.com/package/@snyk/nodejs-runtime-agent , so having the developer-focused documentation at the top makes more sense, in my opinion.
> docs: link to node-woof

- lib/ast.js
- lib/snapshot/index.js
- test/method-detection.test.js
Handle functions with names in expression context, iff they are not being used in a recognised expression context.
Handle functions in `return` statements, which is not an expression context.
We see this in `iter`'s uglified module wrapper. We still don't really see the useful functions in `iter`, but they are ... a mess.
> Support named functions in expression context

- lib/ast.js
- test/method-detection.test.js
Handle some non-identifiers in object literal keys.
`unpackName` could already handle identifiers as we expect, so just extend it to support `Literal`.
> feat: support literals in object keys

- lib/ast.js
- test/method-detection.test.js
Spot this function:
```
if (foo) {
function bar() {}
}
```
We've seen this in `crypto-browserify`.
* `node.alternate` (the `else` block) can be `null`/`undefined`. This is handled by the `if (!node) {` check at the top of `inspectNode`. Would it be clearer to check it explicitly?
> feat: support functions declared in if statements

- demo/index.js
- lib/config.js
- test/config.test.js
- test/e2e.test.js
- test/failures.test.js
Add possible configuration variable that overrides beacon and snapshot URL prefix. 
https://snyksec.atlassian.net/browse/RUN-218
> feat: enable configuration of homebase url origin

- lib/ast.js
- test/method-detection.test.js
Treat:
```
export default function() {}
````
...as if the user had written:
```
module.exports = function() {}
```
> feat: alias export default -> module.exports

- .travis.yml
Use `xenial` (2016) for the travis base image, instead of `trusty` (2014). `bionic` (2018) isn't available yet.
Follows #90.
> Upgrade travis to Xenial

- lib/ast.js
- test/method-detection.test.js
Detect:
```
var Class = Class || (function (Object) {
function foo() {}
});
```
.. as `Class.foo`. We saw this in `es-class`.
> feat: allow lazy || wrapper classes

- package-lock.json
- package.json
needle has a bug with sockets on newer node 12,
we're currently avoiding this newer node 12 to
evade the problem. This bug is fixed in needle
2.5.0, so let's upgrade to that.
https://github.com/tomas/needle/issues/312
> feat: upgrade needle (redirect bug)
